kind: pipeline
type: docker
name: WordPress

steps:
- name: Install
  image: composer:1.10.1
  commands:
    - composer install
  when:
    branch:
    - master
    - homolog

- name: DeployHomolog
  image: alpine:latest
  secrets: [ KEY_HOMOLOG ]
  commands:
    - apk update && apk upgrade && apk add --no-cache rsync git openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$${KEY_HOMOLOG}" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - cat ~/.ssh/id_rsa
  when:
    branch:
    - homolog
  