kind: pipeline
type: docker
name: WordPress

steps:
- name: Install
  image: composer:1.10.1
  commands:
    - composer install
  when:
    branch:
    - master
    - homolog

- name: DeployHomolog
  image: alpine:latest
  environment:
    KEY:
      from_secret: homolog_key
  commands:
    - apk update && apk upgrade && apk add --no-cache rsync openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$KEY" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh root@ssh.linuxsolutions.xyz "ls -la /var/www/"
  when:
    branch:
      - homolog
    status:
      - success