kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang:1.13
  commands:
    - go build
    - go test -v

- name: notify
  image: plugins/slack
  settings:
    channel: dev
    webhook:
      from_secret: endpoint