kind: pipeline
type: docker
name: WordPress

steps:
- name: Install
  image: composer:1.10.1
  commands:
    - composer install
  when:
    branch:
    - master
    - homolog

- name: Test
  image: composer:1.10.1
  commands:
    - apk add libxslt-dev
    - docker-php-ext-install xsl
    - composer install
    - phpdbg -qrr ./vendor/bin/phpunit
  when:
    branch:
      - master
      - homolog
    status:
      - success

- name: DeployHomolog
  image: alpine:latest
  environment:
    KEY:
      from_secret: homolog_key
    PROJECT: wordpress
  commands:
    - apk update && apk upgrade && apk add --no-cache rsync openssh-client
    - mkdir -p ~/.ssh
    - echo -e "$KEY" > ~/.ssh/id_rsa
    - chmod 600  ~/.ssh/id_rsa
    - 'echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - rsync -ahrvz --delete-excluded --chmod="D755,F644" --chown=www-data:www-data -e "ssh -oStrictHostKeyChecking=no " --rsync-path="sudo rsync" * debian@ssh.linuxsolutions.xyz:/var/www/$PROJECT.linuxsolutions.xyz/htdocs
  when:
    branch:
      - homolog
    status:
      - success